DROP TABLE if EXISTS item;
CREATE TABLE IF NOT EXISTS item(
  id SERIAL PRIMARY KEY,
  list_id INTEGER NOT NULL,
  title VARCHAR(78) NOT NULL,
  description VARCHAR(256),
  is_completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ
);

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users(
  id SERIAL PRIMARY KEY,
  username VARCHAR(256) NOT NULL,
  password VARCHAR(256) NOT NULL
);

DROP TABLE IF EXISTS list;
CREATE TABLE IF NOT EXISTS list(
  id SERIAL PRIMARY KEY,
  title VARCHAR(78) NOT NULL
);

DROP TABLE IF EXISTS list_user;
CREATE TABLE IF NOT EXISTS list_user(
  id SERIAL PRIMARY KEY,
  list_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL
)
